package com.bethwelamkenya.personalfinancetrackerspring.domain

enum class TransactionType {
    DEPOSIT, WITHDRAW, TRANSFER_OUT, TRANSFER_IN, TRANSFER_OUT_TO,
    TRANSFER_IN_FROM, DEPOSIT_GOAL, WITHDRAW_GOAL, TRANSFER_GOAL_OUT,
    TRANSFER_GOAL_IN, TRANSFER_GOAL_OUT_TO, TRANSFER_GOAL_IN_FROM
}